name: Build TWRP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install deps
      run: |
        sudo apt update
        sudo apt install -y git-core bc bison flex build-essential zip curl

    - name: Setup repo
      run: |
        mkdir work
        cd work
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-11.0
        repo sync -j$(nproc --all)

    - name: Clone device tree
      run: |
        cd work
        git clone https://github.com/YOUR_GITHUB/device_motorola_cancunf device/motorola/cancunf

    - name: Build recovery
      run: |
        cd work
        source build/envsetup.sh
        lunch omni_cancunf-eng
        mka recoveryimage
